# Generated by Django 5.2.8 on 2025-12-04 10:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactpage_from_address_contactpage_subject_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Nos tarif', max_length=150, verbose_name='Titre principal')),
                ('intro_subtitle', models.TextField(blank=True, default='Voici un exemple de section tarifs que vous pouvez adapter.', help_text="Ex : 'Voici un exemple de section tarif...'", verbose_name='Texte d’intro')),
                ('tarifs', wagtail.fields.StreamField([('tarif', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du tarif', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('features', 4)]], {})}, help_text='Liste complète des tarifs proposés.', verbose_name='Tarifs')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
