# Generated by Django 5.2.9 on 2025-12-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tarifspage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifspage',
            name='image_bas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image_caption',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Légende de l’image'),
        ),
    ]
